default_categories = [
    {'nombre': 'Alquiler', 'icono': '🏠', 'color': '#FFC106'},
    {'nombre': 'Comida', 'icono': '🍽️', 'color': '#FF9800'},
    {'nombre': 'Consultoría', 'icono': '📊', 'color': '#00BCD4'},
    {'nombre': 'Cuidado Personal', 'icono': '💅', 'color': '#795548'},
    {'nombre': 'Educación', 'icono': '🎓', 'color': '#2196F3'},
    {'nombre': 'Entretenimiento', 'icono': '🎬', 'color': '#9C27B0'},
    {'nombre': 'Freelance / Trabajo Independiente', 'icono': '🧑‍💻', 'color': '#2196F3'},
    {'nombre': 'Gastos Varios', 'icono': '📦', 'color': '#8BC34A'},
    {'nombre': 'Ingreso Extraordinario', 'icono': '📈', 'color': '#8BC34A'},
    {'nombre': 'Inversiones', 'icono': '💸', 'color': '#FFC107'},
    {'nombre': 'Plan de ahorro','icono':'💰','color': '#2196F3'},
    {'nombre': 'Rendimientos Bancarios', 'icono': '🏦', 'color': '#795548'},
    {'nombre': 'Salario', 'icono': '💼', 'color': '#4CAF50'},
    {'nombre': 'Salud', 'icono': '🩺', 'color': '#4CAF50'},
    {'nombre': 'Seguros', 'icono': '🛡️', 'color': '#607D8B'},
    {'nombre': 'Suscripciones', 'icono': '🔁', 'color': '#607DFB'},
    {'nombre': 'Transporte', 'icono': '🚗', 'color': '#00BCD4'},
    {'nombre': 'Ventas / Comercio', 'icono': '🛒', 'color': '#FF5722'},
    {'nombre': 'Venta de Productos', 'icono': '🛍️', 'color': '#3F51B5'},
]
